---
- name: install forticlient
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "openfortivpn"
    - "network-manager-fortisslvpn"
    - "network-manager-fortisslvpn-gnome"
  tags: ["forticlient", "install-forticlient"]

- name: ensure variables to set up is defined
  set_fact:
    vpn_ip_address: "{{ lookup('env','VPN_IP_ADDRESS') }}"
    vpn_username: "{{ lookup('env','USER') }}"
    vpn_cert: "{{ lookup('env','VPN_CERT') }}"
  tags: ["forticlient", "copy-azure-templete"]

- name: copy azure vpn setting
  template:
    src: "Azure.j2"
    dest: "/etc/NetworkManager/system-connections/Azure"
    owner: root
    group: root
    mode: 0400
    force: True
  when:
    - vpn_cert | length > 0
    - vpn_ip_address | length > 0
    - vpn_username | length > 0
  tags: ["forticlient", "copy-azure-templete"]
