---
- name: install zsh
  package:
    name: "zsh"
    state: present
  register: install-zsh
  tags: ["zsh", "install-zsh"]

- name: configure zsh to major shell
  command: "usermod --shell /usr/bin/zsh {{ lookup('env','USER') }}"
  tags: ["zsh", "install-zsh"]

- name: Download antibody
  action: get_url
  args:
    url: "{{ antibody_download_url }}"
    dest: "{{ ansible_pkgs_dir }}/antibody-{{ antibody_version }}.tar.gz"
    checksum: "sha256:{{ antibody_checksum }}"
  register: _download_antibody
  until: _download_antibody is succeeded
  tags: ["zsh", "download-antibody"]

- name: unarchive antibody package
  unarchive:
    remote_src: true
    src: "{{ ansible_pkgs_dir }}/antibody-{{ antibody_version }}.tar.gz"
    dest: "/usr/local/bin"
    creates: "/usr/local/bin/antibody"
    extra_opts:
      - "antibody"
  tags: ["zsh", "unarchive-antibody"]

- name: set up antibody executable permissions
  file:
    path: "/usr/local/bin/antibody"
    mode: 0755
  tags: ["zsh", "antibody-permissions"]

- name: clean old zsh files
  become: false
  file:
    state: absent
    path: "{{ running_user_dir }}/.{{ item }}"
  with_items:
    - zlogin
    - zlogout
    - zpreztorc
    - zprofile
    - zshenv
    - zprezto
  tags: ["zsh", "cleanup-old-zsh"]

- name: create zsh config dirs
  become: false
  file:
    state: directory
    path: "{{ running_user_dir }}/.{{ item }}"
  with_items:
    - zsh
    - zkbd
  tags: ["zsh", "create-zshconfig-dir"]

- name: install main zsh config file
  become: false
  copy:
    src: "zshrc"
    dest: "{{ running_user_dir }}/.zshrc"
    mode: 0644
  tags: ["zsh", "install-zshconfig"]

- name: install zsh config files
  become: false
  copy:
    src: "{{ item }}"
    dest: "{{ running_user_dir }}/.zsh/{{ item }}"
  with_items:
    - custom.zsh
    - completion.zsh
    - config.zsh
    - docker.zsh
    - git.zsh
    - golang.zsh
    - less.zsh
    - node.zsh
    - path.zsh
    - plugins
    - python.zsh
    - rpm.zsh
    - ssh.zsh
    - gcp.zsh
    - k8s.zsh
    - ansible.zsh
    - kubectl.zsh
    - vagrant.zsh
    - kops.zsh
  tags: ["zsh", "copy-zshconfig-files"]

- name: install zkbd config files
  become: false
  copy:
    src: "{{ item.src }}"
    dest: "{{ running_user_dir }}/.zkbd/{{ item.dst }}"
    mode: 0644
  with_items:
    - src: zkbd.screen-256color
      dst: screen-256color-:0
    - src: zkbd.xterm-256color
      dst: xterm-256color-:0
  tags: ["zsh", "copy-zkbdconfig-files"]
