---
- include: compat_sudo.yml
- include: Debian_sudo.yml
  when: ansible_os_family == 'Debian'
- include: RedHat_sudo.yml
  when: ansible_os_family == 'RedHat'
- include: install_package_names_sudo.yml
- include: install_additional_packages_sudo.yml
