---
- name: create temporary packages dir
  file:
    path: "{{ ansible_pkgs_dir }}"
    state: directory
  tags: ["pre", "create-tmp-dir"]

- name: install Aptitude Manager Package
  package:
    name: aptitude 
    state: latest
  tags: ["pre", "install-aptitude"]

- name: upgrade all packages
  package:
    name: "*"
    state: latest
  tags: ["pre", "upgrade"]

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - autoconf
    - bzip2
    - clang
    - cockpit
    - flashplugin-installer
    - findutils
    - git    
    - inotify-tools
    - libgdbm-dev
    - libyaml-dev
    - mock
    - postgresql
    - python3
    - python3-dev
    - python3-pip
    - python-dev
    - python-pip    
    - remmina    
    - shellcheck
    - selinux-utils
    - tar
    - tcl-dev
    - terminator
    - tig
    - tix-dev
    - tk-dev
    - util-linux
    - yp-tools
  tags: ["pre", "pre-install-pkgs"]
