---
- hosts: all
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - ../vars/main.yml

  roles:
    - pre
    - geerlingguy.git
    - ngetchell.vscode
    - angstwad.docker_ubuntu
    - andrewrothstein.terraform
    - forticlient
    - wtanaka.gcloud_sdk
    - zsh